apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kanidm-operator-rolebinding-cluster
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kanidm-operator-role-cluster
subjects:
  - kind: ServiceAccount
    name: kanidm-operator-account
    namespace: "kanidm-system"
