apiVersion: apps/v1
kind: Deployment
metadata:
  name: kanidm-operator
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: kanidm-operator
  template:
    metadata:
      labels:
        app.kubernetes.io/name: kanidm-operator
    spec:
      serviceAccountName: kanidm-operator-account
      containers:
      - name: kanidm-tools
        image: docker.io/kanidm/tools
        imagePullPolicy: Always
        command: ["sleep", "infinity"]
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
          requests:
            cpu: 100m
            memory: 100Mi
      - name: kanidm-operator
        image: kanidm-operator
        imagePullPolicy: Always
        resources:
          limits:
            cpu: 100m
            memory: 1024Mi
          requests:
            cpu: 100m
            memory: 100Mi
        livenessProbe:
          initialDelaySeconds: 60 #poetry and kopf together take a long time to initialise
          httpGet:
            path: /healthz
            port: 8080        
        args:
          - --liveness=http://0.0.0.0:8080/healthz
          - --standalone
          - --all-namespaces
          - --verbose
          - /app/start.py
          #- --module
          #- /app/kanidm_operator
