kind: Namespace
apiVersion: v1
metadata:
  name: kanidm
---
apiVersion: kanidm.github.io/v1alpha1
kind: Kanidm
metadata:
  name: kanidm-instance
  namespace: kanidm
spec:
  #All these fields are currently required! TODO make them optional
  version: 1.2.0
  database:
    fsType: other
    storageClass: longhorn
    arcSize: 2048
    storageSize: 1Gi
  domain: idm.eddymir.uk # Put your actual domain here, needed as we issue certificates for it
  certificate:
    issuer: letsencrypt-staging # Put your actual issuer here, something from cert-manager
  logLevel: info
  backup:
    enabled: true
    schedule: "0 9 * * *"
    versions: 7
    storageClass: longhorn # Set your storage class here for the backup
    storageSize: 7Gi
  webPort: 8443
  ldapPort: 3890
  highAvailability:
    enabled: false #HA is not working
    replicas: 1
  ingress:
    annotations:
      nginx.ingress.kubernetes.io/backend-protocol: HTTPS
    enabled: true
    ingressClass: nginx
    trustXForwardedFor: true
---
apiVersion: kanidm.github.io/v1alpha1
kind: User
metadata:
  name: marcus
  namespace: kanidm
spec:
  name: marcus
  displayName: Marcus
  kanidmName: kanidm-instance
  emails:
    - marcus@eddymir.uk
---
apiVersion: kanidm.github.io/v1alpha1
kind: Group
metadata:
  name: bosses
  namespace: kanidm
spec:
  kanidmName: kanidm-instance
  name: bosses
  members: 
    - marcus
---
apiVersion: kanidm.github.io/v1alpha1
kind: OAuth2Client
metadata:
  name: forgejo-oauth
  namespace: kanidm
spec:
  kanidmName: kanidm-instance
  name: forgejo
  displayName: Forgejo
  origin: https://git.eddymir.uk
...