apiVersion: apps/v1
kind: Deployment
metadata:
  name:  kanidm
  namespace: {{ namespace }}
  labels:
    app.kubernetes.io/name: kanidm
    app.kubernetes.io/instance: kanidm
    app.kubernetes.io/version: {{ version }}
    app.kubernetes.io/managed-by: kanidm-operator
    app.kubernetes.io/component: deployment
    app.kubernetes.io/part-of: kanidm
    app.kubernetes.io/created-by: kanidm-operator
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: kanidm
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: kanidm
    spec:
      securityContext:
        # Run as a non root user, but also make the mounts match this user group
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
      containers:
      - name: kanidm-tools
        image: docker.io/kanidm/tools
        imagePullPolicy: Always
        command: ["sleep", "infinity"]
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
          requests:
            cpu: 100m
            memory: 100Mi
        volumeMounts:
        - name: config
          mountPath: /data/server.toml
          subPath: server.toml
          readOnly: true
        - name: certs
          mountPath: /certs
          readOnly: true
        - name: db
          mountPath: /db
        - name: backups
          mountPath: /backups
        - name: data
          mountPath: /data
        - name: cache
          mountPath: /.cache
      - name:  kanidm
        image:  {{ image }}
        imagePullPolicy: IfNotPresent     
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort:  {{ http_port }}
          name:  https
        - containerPort:  {{ ldap_port }}
          name:  ldaps
        volumeMounts:
        - name: config
          mountPath: /data/server.toml
          subPath: server.toml
          readOnly: true
        - name: certs
          mountPath: /certs
          readOnly: true
        - name: db
          mountPath: /db
        - name: backups
          mountPath: /backups
        - name: data
          mountPath: /data
      volumes:
        - name: config
          configMap:
            name:  kanidm-config
        - name: certs
          secret:
            secretName:  kanidm-tls
        - name: db
          persistentVolumeClaim:
            claimName:  kanidm-db
        - name: backups
          persistentVolumeClaim:
            claimName:  kanidm-backups
        - name: data
          emptyDir: {}
        - name: cache
          emptyDir: {}
      restartPolicy: Always
