apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ username | slugify }}-credentials
  namespace: {{ namespace }}
  labels:
    app.kubernetes.io/name: kanidm
    app.kubernetes.io/instance: kanidm
    app.kubernetes.io/version: {{ version }}
    app.kubernetes.io/managed-by: kanidm-operator
    app.kubernetes.io/component: credentials
    app.kubernetes.io/part-of: kanidm
    app.kubernetes.io/created-by: kanidm-operator
data:
  username: {{ username | b64enc }}
  password: {{ password | b64enc }}
