apiVersion: batch/v1
kind: Job
metadata:
  name: {{ name}}
  namespace: {{ namespace }}
spec:
  template:
    spec:
      containers:
      - name: kanidm-tools
        image: {{ image }}
        imagePullPolicy: Always
        env:
        - name: KANIDM_URL
          value: "https://{{ domain }}"
        - name: KANIDM_NAME
          value: {{ username }}
        - name: KANIDM_PASSWORD
          valueFrom:
            secretKeyRef:
              name:  {{ username | slugify }}-credentials
              key: password
        resources:
          limits:
            cpu: 100m
            memory: 1024Mi
          requests:
            cpu: 100m
            memory: 100Mi
        volumeMounts:
        # We need a writable cache for the tools container
        - name: cache
          mountPath: /.cache
        command: 
        - /bin/bash
        - -c
        - |
          kanidm login
          kanidm person create "{{ newuser }}" "{{ displayName }}"
          kanidm person update "{{ newuser }}" --mail "{{ email }}"
          kanidm person get "{{ newuser }}"
      restartPolicy: Never
      volumes:
        - name: cache
          emptyDir: {}
  backoffLimit: 4