apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: accounts.kanidm.github.io
spec:
  scope: Namespaced
  group: kanidm.github.io
  names:
    plural: accounts
    singular: account
    kind: Account
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              required:
                - name
                - displayName
              properties:
                name:
                  type: string
                displayName:
                  type: string
                legalName:
                  type: string
                emails:
                  type: array
                  items:
                    type: string
