apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: groups.kanidm.github.io
spec:
  scope: Namespaced
  group: kanidm.github.io
  names:
    plural: groups
    singular: group
    kind: Group
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              required:
                - name
                - kanidmName
                - members
              type: object
              properties:
                kanidmName:
                  type: string
                name:
                  type: string
                members:
                  type: array
                  items:
                    type: string
