apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: kandim.kanidm.github.io
spec:
  scope: Namespaced
  group: kanidm.github.io
  names:
    plural: kanidms
    singular: kanidm
    kind: Kanidm
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                webPort:
                  type: number
                ldapPort:
                  type: number
                database:
                  type: object
                  properties:
                    path:
                      type: string
                    fsType:
                      type: string
                      enum:
                        - zfs
                        - other
                    arcSize:
                      type: number
                tls:
                  type: object
                  properties:
                    chain:
                      type: string
                    key:
                      type: string
                logLevel:
                  type: string
                  enum:
                    - debug
                    - info
                    - warn
                    - error
                    - fatal
                domain:
                  type: string
                role:
                  type: string
                  enum:
                    - WriteReplica
                    - WriteReplicaNoUI
                    - ReadOnlyReplica
                backup:
                  type: object
                  properties:
                    enabled:
                      type: boolean
                    schedule:
                      type: string
                    versions:
                      type: number
