apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: oauth2-clients.kanidm.github.io
spec:
  scope: Namespaced
  group: kanidm.github.io
  names:
    plural: oauth2-clients
    singular: oauth2-clients
    kind: OAuth2Client
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                name:
                  type: string
                displayName:
                  type: string
                origin:
                  type: string
