apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: password-badlists.kanidm.github.io
spec:
  scope: Namespaced
  group: kanidm.github.io
  names:
    plural: password-badlists
    singular: password-badlist
    kind: PasswordBadlist
    shortNames:
      - pw-badlist
      - pwbl
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            passwords:
              type: array
              items:
                type: string
