apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: service-accounts.kanidm.github.io
spec:
  scope: Namespaced
  group: kanidm.github.io
  names:
    plural: service-accounts
    singular: service-account
    kind: ServiceAccount
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              required:
                - name
                - displayName
              properties:
                name:
                  type: string
                displayName:
                  type: string
                expiresAt:
                  type: string
                  format: date-time
                beginFrom:
                  type: string
                  format: date-time
                secret:
                  type: object
                  properties:
                    name:
                      type: string
                    namespace:
                      type: string
                groups:
                  type: array
                  items:
                    type: string
                ssh:
                  type: array
                  items:
                    type: object
                    oneOf:
                      - tag:
                          type: string
                        publicKey:
                          type: string
                      - tag:
                          type: string
                        generate:
                          type: boolean
                  tokens:
                    type: array
                    items:
                      type: object
                      properties:
                        name:
                          type: string
                        autoRotate:
                          type: boolean
                        expiresAfter:
                          type: string
                          pattern: ^(now|\d{4}-\d{2}-\d{2}([T ]\d{2}:\d{2}:\d{2}(,\d{3})?)?\|\|)([-+])(\d+?)([smhdDWMyY])(/([smhdwMy]))?$
