apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: users.kanidm.github.io
spec:
  scope: Namespaced
  group: kanidm.github.io
  names:
    plural: users
    singular: user
    kind: User
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              required:
                - name
                - displayName
                - kanidmName
                - emails
              properties:
                kanidmName:
                  type: string
                name:
                  type: string
                displayName:
                  type: string
                emails:
                  type: array
                  items:
                    type: string
