name: Build, test, and deploy to Docker Hub

on:
  # Pushes and tags trigger the full workflow
  push:
    branches:
      - 'master'
    tags:
      - 'v*'
  # Pull requests only trigger the unit tests
  pull_request:
    branches:
      - 'master'
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v4
      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11
      - name: Install poetry
        run: |
          pip install poetry
      - name: Set poetry environment
        run: |
          poetry env use 3.11
      - name: Install the project dependencies
        run: poetry install --no-root
      - name: Spin up a k8s cluster
        uses: helm/kind-action@v1
      - name: Run the automated tests
        run: poetry run pytest -v
          
  deploy:
    needs: tests
    runs-on: ubuntu-latest
    steps:
      - name: Extract metadata (tags, labels) for docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ github.repository }} # this will be toastedcrumpets/kanidm-operator
      - name: Login to Docker Hub
        if: github.event_name != 'pull_request'      
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: ${{ github.event_name != 'pull_request' }} # Don't push images for pull requests
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}