name: Testing
on:
  - pull_request

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
  integration-tests:
    needs: unit-tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4

      # Setup kind cluster
      - uses: engineerd/setup-kind@v0.5.0
        with:
          wait: 300s
          version: v0.11.1
          image: kindest/node:v1.20.7
